language: php
sudo: false
dist: trusty

env:
  global:
    - SS_ENVIRONMENT_TYPE="dev"
    - DB=MYSQL

matrix:
  include:
    - php: 5.6
      env:
        - PHPCS_TEST=1
        - PHPUNIT_TEST=1
    - php: 7.0
      env:
        - PHPUNIT_TEST=1
    - php: 7.1
      env:
        - PHPUNIT_COVERAGE_TEST=1

before_script:
  # Init PHP
  - composer self-update || true
  - phpenv rehash
  - phpenv config-rm xdebug.ini || true

  # Install composer dependencies
  - export PATH=~/.composer/vendor/bin:$PATH
  - composer validate
  - if [[ $PHPCS_TEST ]]; then composer global require squizlabs/php_codesniffer:^3 --prefer-dist --no-interaction --no-progress --no-suggest -o; fi
  - composer install --prefer-source --no-interaction --no-progress --no-suggest --optimize-autoloader --verbose --profile

script:
  - if [[ $PHPUNIT_TEST ]]; then vendor/bin/phpunit; fi
  - if [[ $PHPUNIT_COVERAGE_TEST ]]; then phpdbg -qrr vendor/bin/phpunit --coverage-clover=coverage.xml; fi
  - if [[ $PHPCS_TEST ]]; then composer run-script lint; fi

after_success:
  - if [[ $PHPUNIT_COVERAGE_TEST ]]; then bash <(curl -s https://codecov.io/bash) -f coverage.xml; fi
